### ISSUE TITLE
Dockopt for agument parsing

### ISSUE THREAD

**Issue by ntrifunovic** [maxeler/maxminion#1]
We might want to use Docopt for agument parsing: http://docopt.org/

**Comment by alixedi** [comment]
:)

I do not think docopt supports Python 2.6 which comes by default on Maxeler systems.

**Comment by ntrifunovic** [comment]
> docopt is tested with Python 2.5, 2.6, 2.7, 3.2, 3.3 and PyPy.

from: https://pypi.python.org/pypi/docopt

**Comment by alixedi** [comment]
I stand corrected. Doing this today.

**Comment by ntrifunovic** [comment]
:+1:

**Comment by alixedi** [comment]
I believe every time one uses `argparse`, a little puppy dies. 

But:

1) I do not want to incur any dependencies at the moment. 
2) The CLI is simple enough for now.

**Comment by alixedi** [comment]
Turns out `Python 2.6` does not have `argparse` either.

Retro.
